# This workflow is used to run the OpenAgentic assessment on the codebase.
# It creates a pull request with the changes made by the OpenAgentic assessment.

name: AI-Code-Analysis

permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ai-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.7
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run OpenAgentic assessment
        id: assess
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          node scripts/run-code-assessment.js

      - name: Apply patches
        if: steps.assess.outputs.hadChanges == 'true'
        run: |
          echo "$PATCHES" | git apply --whitespace=fix
        env:
          PATCHES: ${{ steps.assess.outputs.patchString }}

      - name: Commit & PR
        if: steps.assess.outputs.hadChanges == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ai/code-improve-${{ github.run_id }}
          title: "AI: automated code improvements"
          body: ${{ steps.assess.outputs.prBody }}
          base: ${{ github.head_ref || github.ref_name }}
